# Created using wingetcreate
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Siberian-Crane.WinCopath
PackageVersion: 1.0.0
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Commands:
  - wcpath
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Siberian-Crane/Win-Copath/releases/download/v1.0.0/wcpath_windows_amd64.exe
    InstallerSha256: B4FFC89AEC56C9BBB4BA4406F3D2A85E6EA43651AB6420C486748C41B1485D53
ManifestType: installer
ManifestVersion: 1.9.0
